### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by diegoaguilar** [IonicaBizau/kindly-license#2]
Would you be interested in integrating spanish support for the contents?

**Comment by IonicaBizau** [comment]
Sure! :sparkles: 

We need to think about how to organize the files, following the i18n. I propose creating the `content` directory containing files like:
- `en.kindly`
- `es.kindly`
- `<short-code>.kindly`

Then, the build script should be adjusted to read them.

**Comment by diegoaguilar** [comment]
I'm pretty interested in translate it. Spanish is my mother tongue and I understand english pretty well.
However, I got not real experience with what i18n stands and its practices. Could you offer me some guide/support?

**Comment by IonicaBizau** [comment]
@diegoaguilar _i18n_ is same with _internationalization_, but shorter. :smile: `"nternationalizatio".length === 18`, so we have: _i18n_. :smile:

**Comment by diegoaguilar** [comment]
God :tongue: ...

**Comment by diegoaguilar** [comment]
Well, I cloned and I'm already writing ...

**Comment by IonicaBizau** [comment]
Ha, this was fixed via #3. :fire: :tada:
